# Generated by Django 3.1.4 on 2021-01-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20201230_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
    ]
