# Generated by Django 3.1.4 on 2021-01-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20210101_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
