# Generated by Django 3.1.4 on 2021-01-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_image_imagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageName',
        ),
    ]
