# Generated by Django 3.1.4 on 2021-01-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0008_image_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
