# Generated by Django 3.1.4 on 2021-01-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_auto_20210102_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='vision_tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
