# Generated by Django 3.1.4 on 2021-01-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0014_auto_20210107_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
