# Generated by Django 3.1.4 on 2021-01-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0021_auto_20210109_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Deleted', 'Deleted')], max_length=8),
        ),
    ]
