# Generated by Django 3.1.4 on 2021-01-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0022_auto_20210109_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('uploaded', 'uploaded'), ('ueleted', 'ueleted')], max_length=8),
        ),
    ]
