# Generated by Django 3.1.4 on 2021-01-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0024_auto_20210109_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploaded_images'),
        ),
    ]
