# Generated by Django 3.1.4 on 2021-01-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0025_auto_20210112_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
